[package]
name = "Pyrs"
version = "0.1.0"
edition = "2021"

[dependencies]
pretty_assertions = "1.4.1"
rug = "1.28.1"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(_YES_)'] }

[features]
default = ["_YES_"]
_YES_ = []
